cache:
  - '%HOMEDRIVE%%HOMEPATH%\.cargo -> .appveyor.yml'
  - '%HOMEDRIVE%%HOMEPATH%\.multirust -> .appveyor.yml'

environment:
  EXAMPLES: calculator console duration membership turbo_blank
  VERBOSE: true
  RUST_BACKTRACE: 1
  matrix:
    # 32-bit
    - RUBY_VERSION: 23
      RUST_HOST: i686-pc-windows-msvc
      RUST_VERSION: stable
    # 64-bit
    - RUBY_VERSION: 23-x64
      RUST_HOST: x86_64-pc-windows-msvc
      RUST_VERSION: stable
    # 64-bit
    - RUBY_VERSION: 23-x64
      RUST_HOST: x86_64-pc-windows-msvc
      RUST_VERSION: nightly

matrix:
  allow_failures:
    - RUST_VERSION: nightly
    - RUST_HOST: i686-pc-windows-msvc

  fast_finish: true

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;C:\Ruby%RUBY_VERSION%\DevKit\bin;C:\Ruby%RUBY_VERSION%\DevKit\mingw\bin;%HOMEDRIVE%%HOMEPATH%\.cargo\bin;%APPVEYOR_BUILD_FOLDER%\ruby\windows_build;%PATH%
  - echo %PATH%
  - set HELIX_ROOT=%APPVEYOR_BUILD_FOLDER%
  - IF NOT EXIST %HOMEDRIVE%%HOMEPATH%\.cargo\bin (curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain %RUST_VERSION% --default-host %RUST_HOST% -y)
  - rustup default %RUST_VERSION%-%RUST_HOST%
  - bash ./scripts/ci-install

test_script:
  - rake

notifications:
  - provider: Slack
    incoming_webhook:
      secure: TNI+AoiNHglfKJMvgc6q13UXc37KvQ4wWFCOTkeqD7KpAYeqX30Xuc3rTMBMABz5hqjdVZHwQV3KoGOgJr52WGtlq2NdIJg7p2j1InTLWfM=
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

build: off
