# TODO: Maybe add caching
cache:
  - '%HOMEDRIVE%%HOMEPATH%\.cargo -> .appveyor.yml'
  - '%HOMEDRIVE%%HOMEPATH%\.multirust -> .appveyor.yml'

environment:
  EXAMPLES: console membership turbo_blank
  VERBOSE: true
  # This isn't expected to pass yet
  #- EXAMPLES="duration"
  matrix:
    # 32-bit
    - RUBY_VERSION: 23
      RUST_HOST: i686-pc-windows-msvc
    # 64-bit
    - RUBY_VERSION: 23-x64
      RUST_HOST: x86_64-pc-windows-msvc

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;C:\Ruby%RUBY_VERSION%\DevKit\bin;C:\Ruby%RUBY_VERSION%\DevKit\mingw\bin;%HOMEDRIVE%%HOMEPATH%\.cargo\bin;%APPVEYOR_BUILD_FOLDER%\ruby\windows_build;%PATH%
  - echo %PATH%
  - set HELIX_ROOT=%APPVEYOR_BUILD_FOLDER%
  - IF NOT EXIST %HOMEDRIVE%%HOMEPATH%\.cargo\bin (curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly --default-host %RUST_HOST% -y)
  - rustup default nightly-%RUST_HOST%
  - bash ./scripts/ci-install

test_script:
  - bash ./scripts/ci-test

notifications:
  - provider: Slack
    incoming_webhook:
      secure: TNI+AoiNHglfKJMvgc6q13UXc37KvQ4wWFCOTkeqD7KpAYeqX30Xuc3rTMBMABz5hqjdVZHwQV3KoGOgJr52WGtlq2NdIJg7p2j1InTLWfM=

build: off
