[package]
name = "helix"
version = "0.1.0"
authors = ["Godhuda <engineering+godhuda@tilde.io>"]
license = "MIT/Apache-2.0"
include = [
  "src/**/*.rs",
  "Cargo.toml"
]

[workspace]

members = ["examples/calculator", "examples/console", "examples/duration", "examples/membership", "examples/turbo_blank"]

[dependencies]
libc = "0.2.0"

[dependencies.cslice]
version = "0.2"

[dependencies.libcruby-sys]
path = "crates/libcruby-sys"
version = "0.5.0-alpha-1"

[dependencies.cstr-macro]
path = "crates/cstr-macro"
version = "0.1.0"
