[package]
name = "membership"
version = "0.1.0"
authors = ["Godhuda <engineering+godhuda@tilde.io>"]

[lib]

crate-type = ["cdylib"]

[dependencies]

libc = "*"

[dependencies.libcruby-sys]

path = "../../crates/libcruby-sys"

[dependencies.helix]

path = "../.."
